### PR TITLE
update url for ocdapi url

### PR DESCRIPTION
**Pull request by fgregg**
this updates the ocd api url in pupa_settings to the dockerized version.

### CODE REVIEW

**Comment by fgregg** [comment]
> the ocd api was a pain, since it was not possible to have the right version of postgist installed and the version of gdal that we need for django 2.0
> 
> i resolved this problem by making a dockerized version of the DB we used for ocd api
>

**Comment by hancush** [comment]
@fgregg How did you set up the container? Manually? Might be nice to have it configured in a Compose file.

**Comment by fgregg** [comment]
it's all done under VC in https://github.com/datamade/api.opencivicdata.org

**Comment by hancush** [comment]
Oh, nice! TY!

**Pull request merged**
